version: '3.8'

services:
  api:
    build: .
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/taskmanagement
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - task-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=taskmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  test:
    build: .
    command: pytest
    environment:
      - CI=true
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/test_taskmanagement
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge
