name: CI

on:
  # Trigger on push to main, but not if it's a CI/CD pipeline commit
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  # Trigger on pull requests to main
  pull_request:
    branches: [ "main" ]

# Cancel any in-progress job or run
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_taskmanagement
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify PostgreSQL connection
      run: |
        echo "Checking PostgreSQL connection..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_taskmanagement -c '\l'
      
    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_taskmanagement
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository_owner }}/task-management-api
      run: |
        # Convert image name to lowercase
        IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        
        # Build the image
        docker build -t $REGISTRY/$IMAGE_NAME_LOWER:latest .
        docker tag $REGISTRY/$IMAGE_NAME_LOWER:latest $REGISTRY/$IMAGE_NAME_LOWER:${{ github.sha }}
        
        # Push both tags
        docker push $REGISTRY/$IMAGE_NAME_LOWER:latest
        docker push $REGISTRY/$IMAGE_NAME_LOWER:${{ github.sha }}
